### ISSUE TITLE
Where is the definition of CROWD_SENSOR?

### ISSUE THREAD

**Issue by Sawyer-Wu** [habicrowd/HabiCrowd#1]
In habitat-lab/habitat/core/embodied_task.py, line 266 attempts to access the attribute "CROWD_SENSOR". However, I couldn't find its definition in either the HabiCrowd repository or the habitat-lab repository. Could you please provide information on where the definition of this attribute is located? Thank you.

**Comment by andvg3** [comment]
Hi @Sawyer-Wu ,

Sorry for late reply. Previously, I had implemented CrowdSensor to manage relative position to humans. However, I've since found it unnecessary and unrealistic, as the robot's navigation should rely solely on RGB observations. Currently, all information about humans can be found in [this file](https://github.com/habicrowd/habitat-lab/blob/1b762d74471a89720359d511df81f095cec57a00/habitat/sims/habitat_simulator/habitat_simulator.py#L289). To access information on all controlled robots, you can use `self.bot_obj`.

I hope my answer helps and look forward to your any further questions.

**Comment by Sawyer-Wu** [comment]
Thanks for your reply. I will try to delete CrowdSensor later.

**Comment by andvg3** [comment]
Closed due to inactivity.

**Comment by Sawyer-Wu** [comment]
您好，你的邮件我已经收到，我会尽快给您回复，谢谢。
